# Generated by Django 4.2.17 on 2025-01-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_favorite_recipe_alter_favorite_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
    ]
