# Generated by Django 4.2.17 on 2025-01-13 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={},
        ),
    ]
