# Generated by Django 4.2.17 on 2025-01-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_subscription_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
    ]
